### ISSUE TITLE
Allow for red/orange text as in the original game

### ISSUE THREAD

**Issue by LuisMayo** [LuisMayo/objection_engine#41]

**Comment by Meorge** [comment]
I'd like to take a stab at implementing this, but from the research I've done so far it sounds like it may involve a fair bit of work on how text is rendered. My current thought is to follow a procedure something like the following:
1. Start with an input string like so:
```
Hello, my name is \col{FF0000}Phoenix\col{default} and I am a \col{FF0000}defense attorney\col{default}. \col{0000FF}(Hopefully a good one...)
```
In this example syntax, the command `\col{NEW_COLOR}` would set the color of following text. Of course, it wouldn't necessarily need to be this exact syntax, but I think it would make the following steps easier than nested tags like HTML.

2. Move through the string, keeping track of the indices of color commands and deleting them from the original string. We'd then end up with:
```
Hello, my name is Phoenix and I am a defense attorney. (Hopefully a good one...)
```
as well as the indices:
* 18 color = #FF0000
* 25 color = default
* 37 color = #FF0000
* 53 color = default
* 55 color = #0000FF

3. Measure the stripped string out, splitting it at the appropriate points for newlines. We might then end up with the following list of strings:
```py
[
    "Hello, my name is Phoenix ",
    "and I am a defense attorney. ",
    "(Hopefully a good one...)"
]
```
Here I chose to not strip whitespace, but that would probably be a wise thing to do. If so, we'll need to correct the indices impacted by it.

4. Using the indices, create a new list, where each item is a chunk of text that can be rendered all at once...
```py
[
    [
        TextChunk("Hello, my name is ", color=default),
        TextChunk("Phoenix", color=0xFF0000),
        TextChunk(" ", color=default)
    ],
    [
        TextChunk("and I am a ", color=default),
        TextChunk("defense attorney", color=0xFF0000),
        TextChunk(". ", color=default)
    ],
    [
        TextChunk("(Hopefully a good one...)", color=0x0000FF)
    ]
]
```
Within this list, each sublist represents one line of text. We'd render each `TextChunk`, then measure its width and render the next `TextChunk` with that offset.


The end result of all this is that we *should* be able to render rich text... but I'm worried this may a) be overcomplicated and b) break for some scenarios like Arabic text. Before setting off on a big change like this, I suppose it'd be good to feel confident that this would be the way to go and that there isn't an easier way to accomplish this 😅 .

**Comment by LuisMayo** [comment]
Hi

Thanks for the contribution. I haven't taken a look at the Pillow API but it seems that it doesn't support inline coloring.

That being said I can't imagine a better way to do it than the one you explained here. The only variant I can think off is to expose the texts chunk as part of the obiection_engine API so we don't have to do the inline parsing thing, but to be honest the inline parsing thing is way more easy for the consumer so I'd still go for that.

I'm also worried about how this is going to play with right-to-left languages since I understand that what we gotta do is save the coordinates and play a bit of math about it so we should use different logic for both LTR and RTL

**Comment by Meorge** [comment]
That sounds a lot like what I was thinking. Worst case scenario, this text splitting technique could be ignored for RTL languages and/or languages where the characters connect to each other, like Arabic.

I suppose this is outside the scope of this particular issue, but something I was thinking about was drawing text character-by-character instead of chunk-by-chunk. This would allow us to control the kerning/spacing between characters and make text more closely resemble how it looks in the games (right now, the letters seem too close to each other). This would make things even harder yet for fonts with joined characters, though... 😅 .

I may toy with these approaches over the next couple of days and see what comes of them, while waiting to see if anyone else has thoughts on the best approach.

**Comment by Meorge** [comment]
I have some progress to share! Nothing's yet running in the engine itself, but I (appear to) have a basic tag parser set up. With the input string:
```
"Hello, my name is <red>Bob</red> and I like to <green>eat avocados</green>. <shake/>Yum! <blue>(Wish I had more...)</blue>"
```
I can get a list of either
* lists of individual characters in each line, and what tags apply to them, like so:
```py
[
    [
        ("H", []),
        ("e", []),
        ("l", []),
        ("l", []),
        ("o", []),
        (",", []),
        (" ", []),
        ("m", []),
        ("y", []),
        (" ", []),
        ("n", []),
        ("a", []),
        ("m", []),
        ("e", []),
        (" ", []),
        ("i", []),
        ("s", []),
        (" ", []),
        ("B", ["red"]),
        ("o", ["red"]),
        ("b", ["red"]),
        (" ", []),
        ("a", []),
        ("n", []),
        ("d", []),
        (" ", []),
        ("I", []),
        (" ", []),
        ("l", []),
        ("i", []),
        ("k", []),
        ("e", []),
        (" ", []),
        ("t", []),
        ("o", []),
        (" ", []),
        ("e", ["green"]),
        ("a", ["green"]),
        ("t", ["green"]),
    ],
    [
        ("a", ["green"]),
        ("v", ["green"]),
        ("o", ["green"]),
        ("c", ["green"]),
        ("a", ["green"]),
        ("d", ["green"]),
        ("o", ["green"]),
        ("s", ["green"]),
        (".", []),
        (" ", []),
        ("Y", ["shake"]),
        ("u", []),
        ("m", []),
        ("!", []),
        (" ", []),
        ("(", ["blue"]),
        ("W", ["blue"]),
        ("i", ["blue"]),
        ("s", ["blue"]),
        ("h", ["blue"]),
        (" ", ["blue"]),
        ("I", ["blue"]),
        (" ", ["blue"]),
        ("h", ["blue"]),
        ("a", ["blue"]),
        ("d", ["blue"]),
        (" ", ["blue"]),
        ("m", ["blue"]),
        ("o", ["blue"]),
        ("r", ["blue"]),
        ("e", ["blue"]),
        (".", ["blue"]),
        (".", ["blue"]),
        (".", ["blue"]),
        (")", ["blue"]),
    ],
]
```

* or lists of continuous chunks of text styled the same, like so:
```py
[
    [
        ("Hello, my name is ", []),
        ("Bob", ["red"]),
        (" and I like to ", []),
        ("eat", ["green"]),
    ],
    [
        ("avocados", ["green"]),
        (". ", []),
        ("Y", ["shake"]),
        ("um! ", []),
        ("(Wish I had more...)", ["blue"]),
    ],
]
```

Next step will be drawing the text chunks. I suspect/hope this won't be too difficult - both approaches will be able to use the same code, since they're fundamentally doing the same thing.

**Comment by Meorge** [comment]
Good news! I've made more progress on this, and it seems to be working for Latin alphabet text now! Unfortunately, text wrapping for other languages (and RTL text in general) seems to have broken in the process 😅 ...

https://user-images.githubusercontent.com/9957987/198838586-2e9fac20-f5c5-48ca-88d8-52ad5d750678.mp4

I'm trying to use the [ImageDraw.textlength()](https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#PIL.ImageDraw.ImageDraw.textlength) function to measure the width of each continuous string chunk, then offset subsequent chunks by that amount. However, for a lot of the non-English text, the function throws an error like so:
```
Traceback (most recent call last):
  ...
  File "/Users/malcolmanderson/Documents/Repositories/objection_engine/objection_engine/beans/text.py", line 125, in render
    add_to_x_offset = draw.textlength(chunk.text)
  File "/Users/malcolmanderson/Library/Caches/pypoetry/virtualenvs/objection-engine-Acfxk5DR-py3.9/lib/python3.9/site-packages/PIL/ImageDraw.py", line 663, in textlength
    return font.getlength(text, mode, direction, features, language)
  File "/Users/malcolmanderson/Library/Caches/pypoetry/virtualenvs/objection-engine-Acfxk5DR-py3.9/lib/python3.9/site-packages/PIL/ImageFont.py", line 197, in getlength
    width, height = self.font.getsize(text)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u062d' in position 0: ordinal not in range(256)
```
As a workaround, I'm currently having it fall back to using the deprecated [ImageFont.getsize()](https://pillow.readthedocs.io/en/stable/reference/ImageFont.html#PIL.ImageFont.FreeTypeFont.getsize) function.

At this point, overall the remaining issues I see are:
* Text wrapping for other languages needs to be fixed
* RTL rendering of multiple chunks is very wrong (within each chunk I think they're RTL, but chunks themselves are LTR)

**Comment by Meorge** [comment]
I did a little more experimentation today with the text wrapping for other languages (specifically, Japanese) and found that apparently Python's `textwrap` module doesn't know how to wrap it accurately.
```
Python 3.11.0 (v3.11.0:deaf509e8f, Oct 24 2022, 14:43:23) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from textwrap import fill
>>> fill("気やすく呼ぶんじゃないよ!このギザギザ男がッ!アンタのせいで、オバチャンまた、ワルモノにされちまったョ!")
'気やすく呼ぶんじゃないよ!このギザギザ男がッ!アンタのせいで、オバチャンまた、ワルモノにされちまったョ!'
>>> fill("Hello how are you this is a sentence that is as long as the Japanese text above, but it should wrap!")
'Hello how are you this is a sentence that is as long as the Japanese\ntext above, but it should wrap!'
```

I'll see if I can adapt the line-wrapping code that the current main branch has to this new text system - that should fix those problems.

I'm unfortunately still stumped on how to approach the RTL rendering situation... Perhaps once the text-wrapping issue is resolved, the feature branch could be merged with the caveat that the text-color tags don't work correctly with RTL, but encourage others to work on it if they find it necessary? It feels like a major cop-out, but at the same time I'd feel bad about holding back this feature from *everyone* just because it doesn't work correctly with some languages (especially since the feature is optional and requires extra work on the text in order for it to take effect).

**Comment by LuisMayo** [comment]
I agree on merging and opening an issue. I'd add code to check if the language is rtl and just don't apply the color managing in that case at all.

However, there may be some things we can still try. The right to left approach is hard because text is left-aligned even if the writing itself is rtl, isn't it? In that case we may be able to instruct pillow to right-align the text for rtl languages, that way we only would need to mirror our calculations for ltr and rtl languages. Do you know if that's possible?

About the new line breaking in japanese problem, until now the engine has been using `spacy`. Does `spacy` show a similar problem as `textwrap` does?

Thanks a lot for your job in this and other issues!

**Comment by Meorge** [comment]
> In that case we may be able to instruct pillow to right-align the text for rtl languages, that way we only would need to mirror our calculations for ltr and rtl languages. Do you know if that's possible?

I think that should be possible! The biggest hurdle I've seen there is detecting whether or not text is RTL so that the styling can be applied. We could do this by scoring the text and applying the RTL algorithm if an RTL font is the best one.

> About the new line breaking in japanese problem, until now the engine has been using `spacy`. Does `spacy` show a similar problem as `textwrap` does?

It appears that `spacy` doesn't recognize sentence breaks in Japanese. I put together this little script using code from `anim.py`:

```py
from textwrap import wrap
import spacy

nlp = spacy.blank("xx")
nlp.add_pipe("sentencizer")

en_text = "Here are a bunch of sentences in English. There are so many! They just keep coming! This textbox should go across multiple lines."
ja_text = "気やすく呼ぶんじゃないよ!このギザギザ男がッ!アンタのせいで、オバチャンまた、ワルモノにされちまったョ!"

def do_wrapping(text):
    tokens = nlp(text)
    sentences = [sent.text for sent in tokens.sents]
    joined_sentences = []
    i = 0
    while i < len(sentences):
        sentence = sentences[i]
        if len(sentence) > 85: # Long sentences should be wrapped to multiple shorter lines
            text_chunks = [chunk for chunk in wrap(sentence, 85)]
            joined_sentences = [*joined_sentences, *text_chunks]
            i += 1
        else:
            if i + 1 < len(sentences) and len(f"{sentence} {sentences[i+1]}") <= 85: # Maybe we can join two different sentences
                joined_sentences.append(sentence + " " + sentences[i+1])
                i += 2
            else:
                joined_sentences.append(sentence)
                i += 1

    return joined_sentences

print(f"EN: {do_wrapping(en_text)}")
print(f"JA: {do_wrapping(ja_text)}")
```
The following is printed:
```
EN: ['Here are a bunch of sentences in English. There are so many!', 'They just keep coming! This textbox should go across multiple lines.']
JA: ['気やすく呼ぶんじゃないよ!このギザギザ男がッ!アンタのせいで、オバチャンまた、ワルモノにされちまったョ!']
```

It looks to me like we'll need to use the strategy that `fit_words_within_width()` and `split_str_into_newlines()` is using - getting the active font and adding the characters to an empty string until the textbox width would be exceeded based on the font characters' width, then considering that a newline.

**Comment by Meorge** [comment]
Is there a particular need/use for splitting using sentences, instead of just using the `wrap()` method? It looks to me like it doesn't significantly impact the results for English text, but the code is much simpler. I was thinking we could call `wrap()` to do the initial wrapping, then from there measure the strings using the font to split them further as necessary.

**Comment by LuisMayo** [comment]
As with a lot of code in the engine, I didn't write it, but it was inherited from the [reddit bot](https://github.com/micah5/ace-attorney-reddit-bot) so I can't know the specifics of why it was made that way.

That being said I've always supposed that if we split by sentences the video would be more interesting to get the textbox=sentence (when possible). This is also how [the games work](https://www.youtube.com/watch?v=C0FSmuVulJM).

However, the current code for sentences splitting is overcomplicated. I must agree on that one. I would stick to a basic sentence split (using spacy should be fine) then furthering it with wrap since the current approach is too complex anyway

**Comment by Meorge** [comment]
It's been a couple of days so I wanted to give an update.

For now, it looks like using the existing algorithm is working well! ...Except for Chinese, for some reason 🥲 

Here's a video comparison of the main branch and my text-tags branch. It's hard to tell how much of the desync is just from the video players not starting at the same time, and how much of it is other stuff, but there are definitely some differences in timing. Overall though, I don't think it's a huge issue, except for the Chinese text not all showing up.

https://user-images.githubusercontent.com/9957987/200048342-cf673957-6462-4b6c-99d5-a9017f882d74.mov

<img width="1061" alt="Screenshot 2022-11-04 at 11 00 58 AM" src="https://user-images.githubusercontent.com/9957987/200045860-6e37c55c-b830-425d-b0d3-6fdae2bf91a6.png">

"Expected" here is the main branch, and "What it's doing" is the rich-text version. As far as I could tell in the example script, all of the other text seems to be wrapped without issues, so I don't know why the Chinese is being wrapped differently and/or truncated.

I've got other things I need to take care of for now, but I'm hoping when I'm able to return to it this won't be too difficult a thing to figure out! Once this is resolved, I think the RTL support will be the last thing to do before it's ready to be merged. 😄

**Comment by Meorge** [comment]
Looks like the issue was that it was using a different font to measure the text width. It's fixed now:
<img width="670" alt="Screenshot 2022-11-04 at 5 07 04 PM" src="https://user-images.githubusercontent.com/9957987/200091473-bb5717e0-fc1e-413c-8191-27408cc2e982.png">

Last task is RTL support! 😄
